spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://120.24.35.246:3306/house_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: house
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
#  映射文件位置
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8080
#  ssl:
#    key-alias: myhttps
#    key-store: classpath:wen_key.p12
#    key-store-password: leaves

